---
collections:
  - name: ansible.posix
    version: '1.5.4'
  - name: ansible.utils
    version: '5.0.0'
  - name: ansible.eda
    version: '1.4.7'
  - name: ansible.netcommon
    version: '7.0.0'
  - name: ansible.controller
    version: '4.5.7'
  - name: community.crypto
    version: '2.20.0'
  - name: community.general
    version: '8.3.0'
  - name: community.dns
    version: '3.0.1'
  - name: azure.azcollection
    version: '2.4.0'
  - name: redhat.rhel_idm
    version: '1.12.1'
  - name: redhat.rhel_system_roles
    version: '1.23.0'
  - name: redhat.satellite_operations
    version: '3.0.0'
  - name: redhat.satellite
    version: '4.0.0'
  - name: infra.aap_utilities
    version: '2.5.1'
  - name: infra.controller_configuration
    version: '2.7.1'
  - name: infra.ee_utilities
    version: '3.2.0'
  - name: infra.ah_configuration
    version: '2.0.6'
  - name: infra.leapp
    version: '1.3.1'
  - name: containers.podman
    version: '1.13.0'

roles:
  - name: RedHatOfficial.rhel9_cis
  - name: monolithprojects.github_actions_runner
