---
- name: "Copy the scap file to target"
  become: true
  ansible.builtin.copy:
    src: "{{ scap_content.scap_file }}"
    dest: "{{ scap_content.scap_file }}"
    owner: root
    group: root
    mode: "0644"
  when: "scap_content.scap_file is defined"

- name: "Ensure the scap content is loaded"
  redhat.satellite.scap_content:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_server_url }}"
    title: "{{ scap_content.title }}"
    scap_file: "{{ scap_content.scap_file | default(omit) }}"
    locations: "{{ scap_content.locations | default(omit) }}"
    organizations: "{{ scap_content.organizations | default(omit) }}"
    updated_title: "{{ scap_content.updated_title | default(omit) }}"
    state: "{{ scap_content.state | default(omit) }}"
